# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#theme-meta-data for more info

name = "Trostsville Primary School Theme"
license = "MIT"
licenselink = ""
description = "A modern, responsive theme for Trostsville Primary School"
homepage = "https://www.trotsvilleprimaryschool.co.za/"
tags = ["school", "education", "tailwind"]
features = ["responsive", "tailwind", "blog", "contact form"]
min_version = "0.80.0"

[author]
  name = "Trostsville Primary School"
  homepage = "https://www.trotsvilleprimaryschool.co.za/"
